
package Vista;



public class FormReporteVentas extends javax.swing.JInternalFrame {

    
 
    
    public FormReporteVentas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
<<<<<<< HEAD
        jLabel17 = new javax.swing.JLabel();
        jcbxMoneda = new javax.swing.JComboBox<>();
        jbntVVendedor = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jbntVCliente = new javax.swing.JButton();
        jbntVProducto = new javax.swing.JButton();
        jdcFFin = new com.toedter.calendar.JDateChooser();
        jdcFInicio = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jbtnCVentas = new javax.swing.JButton();
=======
        jSeparator11 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboMoneda = new javax.swing.JComboBox<>();
        btn_vemplea = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        btn_vclientes = new javax.swing.JButton();
        btn_vprod = new javax.swing.JButton();
        jdcDateEnd = new com.toedter.calendar.JDateChooser();
        jdcDateInit = new com.toedter.calendar.JDateChooser();
        btn_getVentas = new javax.swing.JButton();
>>>>>>> 59b9cee1b210ed698810531a8e473f6910570d2c

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jtblDatos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 850, 260));

        jPanel1.setBackground(new java.awt.Color(0, 173, 188));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, -40, 150, 160));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REPORTE DE VENTAS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 300, 50));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/favicon.png"))); // NOI18N
        jLabel2.setText("INFOCOM SAC");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 50));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 850, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
<<<<<<< HEAD
=======
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 270, 10));
>>>>>>> 59b9cee1b210ed698810531a8e473f6910570d2c

        jLabel17.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel17.setText("FECHA DE INICIO");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, -1));

<<<<<<< HEAD
        jcbxMoneda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbxMoneda.setForeground(new java.awt.Color(153, 153, 153));
        jcbxMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEN", "USD" }));
        jcbxMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxMonedaActionPerformed(evt);
            }
        });
        jPanel3.add(jcbxMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 270, 20));

        jbntVVendedor.setBackground(new java.awt.Color(47, 123, 123));
        jbntVVendedor.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        jbntVVendedor.setForeground(new java.awt.Color(255, 255, 255));
        jbntVVendedor.setText("VENTAS POR VENDEDOR");
        jbntVVendedor.setBorder(null);
        jPanel3.add(jbntVVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 270, 30));
=======
        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel8.setText("MONEDA:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 170, 20));

        comboMoneda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboMoneda.setForeground(new java.awt.Color(153, 153, 153));
        comboMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEN", "USD" }));
        comboMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMonedaActionPerformed(evt);
            }
        });
        jPanel3.add(comboMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 270, 30));

        btn_vemplea.setBackground(new java.awt.Color(47, 123, 123));
        btn_vemplea.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        btn_vemplea.setForeground(new java.awt.Color(255, 255, 255));
        btn_vemplea.setText("VENTAS POR VENDEDOR");
        btn_vemplea.setBorder(null);
        jPanel3.add(btn_vemplea, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 270, 30));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 270, 10));
>>>>>>> 59b9cee1b210ed698810531a8e473f6910570d2c

        jLabel18.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel18.setText("MONEDA");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 250, -1));

<<<<<<< HEAD
        jbntVCliente.setBackground(new java.awt.Color(47, 123, 123));
        jbntVCliente.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        jbntVCliente.setForeground(new java.awt.Color(255, 255, 255));
        jbntVCliente.setText("VENTAS POR CLIENTE");
        jbntVCliente.setBorder(null);
        jPanel3.add(jbntVCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 270, 30));

        jbntVProducto.setBackground(new java.awt.Color(47, 123, 123));
        jbntVProducto.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        jbntVProducto.setForeground(new java.awt.Color(255, 255, 255));
        jbntVProducto.setText("VENTAS POR PRODUCTO");
        jbntVProducto.setBorder(null);
        jPanel3.add(jbntVProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 270, 30));
        jPanel3.add(jdcFFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 270, -1));
        jPanel3.add(jdcFInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 270, -1));

        jLabel19.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel19.setText("FECHA DE FIN");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 250, -1));

        jLabel20.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel20.setText("FECHA DE FIN");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 250, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 850, 160));

        jbtnCVentas.setBackground(new java.awt.Color(47, 123, 123));
        jbtnCVentas.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        jbtnCVentas.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCVentas.setText("CONSULTAR VENTAS");
        jbtnCVentas.setBorder(null);
        jPanel2.add(jbtnCVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 770, 30));
=======
        btn_vclientes.setBackground(new java.awt.Color(47, 123, 123));
        btn_vclientes.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        btn_vclientes.setForeground(new java.awt.Color(255, 255, 255));
        btn_vclientes.setText("VENTAS POR CLIENTE");
        btn_vclientes.setBorder(null);
        jPanel3.add(btn_vclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 270, 30));

        btn_vprod.setBackground(new java.awt.Color(47, 123, 123));
        btn_vprod.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        btn_vprod.setForeground(new java.awt.Color(255, 255, 255));
        btn_vprod.setText("VENTAS POR PRODUCTO");
        btn_vprod.setBorder(null);
        jPanel3.add(btn_vprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 270, 30));
        jPanel3.add(jdcDateEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 270, -1));
        jPanel3.add(jdcDateInit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 270, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 850, 160));

        btn_getVentas.setBackground(new java.awt.Color(47, 123, 123));
        btn_getVentas.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        btn_getVentas.setForeground(new java.awt.Color(255, 255, 255));
        btn_getVentas.setText("CONSULTAR VENTAS");
        btn_getVentas.setBorder(null);
        jPanel2.add(btn_getVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 770, 30));
>>>>>>> 59b9cee1b210ed698810531a8e473f6910570d2c

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 880, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void jcbxMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxMonedaActionPerformed
=======
    private void comboMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMonedaActionPerformed
>>>>>>> 59b9cee1b210ed698810531a8e473f6910570d2c

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormReporteVentas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
=======
    public javax.swing.JButton btn_getVentas;
    public javax.swing.JButton btn_vclientes;
    public javax.swing.JButton btn_vemplea;
    public javax.swing.JButton btn_vprod;
    public javax.swing.JComboBox<String> comboMoneda;
>>>>>>> 59b9cee1b210ed698810531a8e473f6910570d2c
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
<<<<<<< HEAD
    public javax.swing.JButton jbntVCliente;
    public javax.swing.JButton jbntVProducto;
    public javax.swing.JButton jbntVVendedor;
    public javax.swing.JButton jbtnCVentas;
    public javax.swing.JComboBox<String> jcbxMoneda;
    public com.toedter.calendar.JDateChooser jdcFFin;
    public com.toedter.calendar.JDateChooser jdcFInicio;
    public javax.swing.JTable jtblDatos;
=======
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    public javax.swing.JTable jTable1;
    public com.toedter.calendar.JDateChooser jdcDateEnd;
    public com.toedter.calendar.JDateChooser jdcDateInit;
>>>>>>> 59b9cee1b210ed698810531a8e473f6910570d2c
    // End of variables declaration//GEN-END:variables
}
