
package Vista;



public class FormClientes extends javax.swing.JInternalFrame {

    
 
    
    public FormClientes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtDireccion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jtxtNombreRazon = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jtxtCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbxTipoDoc = new javax.swing.JComboBox<>();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnConsultar = new javax.swing.JButton();
        jbtnActualizar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jcbxSexo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jtxtId = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jspCelular = new javax.swing.JSpinner();
        jspNumDoc = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jtxtApellidos = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jtblDatos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 790, 580));

        jPanel1.setBackground(new java.awt.Color(0, 173, 188));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, -30, 150, 160));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/favicon.png"))); // NOI18N
        jLabel2.setText("INFOCOM SAC");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 50));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTRO Y MANTENIMIENTO DEL CLIENTE / EMPRESA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 670, 60));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1240, 100));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel5.setText("NO. DE DOCUMENTO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 400, 20));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel6.setText("NOMBRE/RAZÓN SOCIAL");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 180, 20));

        jtxtDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtDireccion.setForeground(new java.awt.Color(153, 153, 153));
        jtxtDireccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtxtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDireccionActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 400, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 400, 10));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel7.setText("DIRECCIÓN");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 80, 20));

        jtxtNombreRazon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtNombreRazon.setForeground(new java.awt.Color(153, 153, 153));
        jtxtNombreRazon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtxtNombreRazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreRazonActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtNombreRazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 400, 20));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 400, 10));

        jtxtCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        jtxtCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtxtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCorreoActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 400, 20));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel8.setText("CORREO ELECTRÓNICO");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 160, 20));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 400, 10));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel9.setText("SEXO");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 50, 20));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel10.setText("TELÉFONO / CELULAR");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 150, 20));

        jcbxTipoDoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbxTipoDoc.setForeground(new java.awt.Color(153, 153, 153));
        jcbxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "RUC" }));
        jcbxTipoDoc.setBorder(null);
        jPanel2.add(jcbxTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 400, 30));

        jbtnRegistrar.setBackground(new java.awt.Color(47, 123, 123));
        jbtnRegistrar.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        jbtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegistrar.setText("REGISTRAR");
        jbtnRegistrar.setBorder(null);
        jPanel2.add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 400, 30));

        jbtnConsultar.setBackground(new java.awt.Color(47, 123, 123));
        jbtnConsultar.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        jbtnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnConsultar.setText("CONSULTAR");
        jbtnConsultar.setBorder(null);
        jPanel2.add(jbtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 110, 30));

        jbtnActualizar.setBackground(new java.awt.Color(47, 123, 123));
        jbtnActualizar.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        jbtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnActualizar.setText("ACTUALIZAR");
        jbtnActualizar.setBorder(null);
        jPanel2.add(jbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 110, 30));

        jbtnEliminar.setBackground(new java.awt.Color(47, 123, 123));
        jbtnEliminar.setFont(new java.awt.Font("Roboto Light", 3, 14)); // NOI18N
        jbtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminar.setText("ELIMINAR");
        jbtnEliminar.setBorder(null);
        jPanel2.add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, 110, 30));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel11.setText("TIPO DE DOCUMENTO");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 400, 20));

        jcbxSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbxSexo.setForeground(new java.awt.Color(153, 153, 153));
        jcbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));
        jcbxSexo.setBorder(null);
        jPanel2.add(jcbxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 400, 30));

        jLabel12.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel12.setText("ID");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 400, 20));

        jtxtId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtId.setForeground(new java.awt.Color(153, 153, 153));
        jtxtId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtxtId.setEnabled(false);
        jPanel2.add(jtxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 400, 20));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 400, 10));
        jPanel2.add(jspCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 400, -1));
        jPanel2.add(jspNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 400, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel13.setText("APELLIDOS");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, 20));

        jtxtApellidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtApellidos.setForeground(new java.awt.Color(153, 153, 153));
        jtxtApellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtxtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtApellidosActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 400, 20));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 400, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNombreRazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreRazonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreRazonActionPerformed

    private void jtxtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDireccionActionPerformed

    private void jtxtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCorreoActionPerformed

    private void jtxtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtApellidosActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormClientes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JButton jbtnActualizar;
    public javax.swing.JButton jbtnConsultar;
    public javax.swing.JButton jbtnEliminar;
    public javax.swing.JButton jbtnRegistrar;
    public javax.swing.JComboBox<String> jcbxSexo;
    public javax.swing.JComboBox<String> jcbxTipoDoc;
    public javax.swing.JSpinner jspCelular;
    public javax.swing.JSpinner jspNumDoc;
    public javax.swing.JTable jtblDatos;
    public javax.swing.JTextField jtxtApellidos;
    public javax.swing.JTextField jtxtCorreo;
    public javax.swing.JTextField jtxtDireccion;
    public javax.swing.JTextField jtxtId;
    public javax.swing.JTextField jtxtNombreRazon;
    // End of variables declaration//GEN-END:variables
}
