/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author MartiPE
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpContenedor = new javax.swing.JDesktopPane();
        jlFechaHora = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlFechaHoraDatos = new javax.swing.JLabel();
        jlUsuarioDatos = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        jmiMantenimientoClientes = new javax.swing.JMenuItem();
        jmProductos = new javax.swing.JMenu();
        jmiMantenimientoCategorias = new javax.swing.JMenuItem();
        jmiMantenimientoProductos = new javax.swing.JMenuItem();
        jmiMantenimientoStock = new javax.swing.JMenuItem();
        jmVentas = new javax.swing.JMenu();
        jmiRegistroVentas = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jmiReporteVentas = new javax.swing.JMenuItem();
        jmUsuario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpContenedor.setBackground(new java.awt.Color(204, 255, 255));

        jlFechaHora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlFechaHora.setText("Fecha y Hora:");

        jlUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlUsuario.setText("Datos Usuario:");

        jlFechaHoraDatos.setText("dateTime");

        jlUsuarioDatos.setText("userData");

        jdpContenedor.setLayer(jlFechaHora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpContenedor.setLayer(jlUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpContenedor.setLayer(jlFechaHoraDatos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpContenedor.setLayer(jlUsuarioDatos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpContenedorLayout = new javax.swing.GroupLayout(jdpContenedor);
        jdpContenedor.setLayout(jdpContenedorLayout);
        jdpContenedorLayout.setHorizontalGroup(
            jdpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpContenedorLayout.createSequentialGroup()
                .addContainerGap(1133, Short.MAX_VALUE)
                .addGroup(jdpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpContenedorLayout.createSequentialGroup()
                        .addComponent(jlUsuario)
                        .addGap(12, 12, 12)
                        .addComponent(jlUsuarioDatos))
                    .addGroup(jdpContenedorLayout.createSequentialGroup()
                        .addComponent(jlFechaHora)
                        .addGap(18, 18, 18)
                        .addComponent(jlFechaHoraDatos)))
                .addContainerGap())
        );
        jdpContenedorLayout.setVerticalGroup(
            jdpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpContenedorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jdpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUsuario)
                    .addComponent(jlUsuarioDatos))
                .addGap(6, 6, 6)
                .addGroup(jdpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlFechaHora)
                    .addComponent(jlFechaHoraDatos)))
        );

        jmClientes.setText("Clientes");

        jmiMantenimientoClientes.setText("Mantenimiento de clientes");
        jmClientes.add(jmiMantenimientoClientes);

        jMenuBar1.add(jmClientes);

        jmProductos.setText("Productos");

        jmiMantenimientoCategorias.setText("Mantenimiento de categorías");
        jmiMantenimientoCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMantenimientoCategoriasActionPerformed(evt);
            }
        });
        jmProductos.add(jmiMantenimientoCategorias);

        jmiMantenimientoProductos.setText("Mantenimiento de productos");
        jmiMantenimientoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMantenimientoProductosActionPerformed(evt);
            }
        });
        jmProductos.add(jmiMantenimientoProductos);

        jmiMantenimientoStock.setText("Mantenimiento de stock");
        jmiMantenimientoStock.setToolTipText("");
        jmiMantenimientoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMantenimientoStockActionPerformed(evt);
            }
        });
        jmProductos.add(jmiMantenimientoStock);

        jMenuBar1.add(jmProductos);

        jmVentas.setText("Ventas");

        jmiRegistroVentas.setText("Registro de ventas");
        jmVentas.add(jmiRegistroVentas);

        jMenuBar1.add(jmVentas);

        jmReportes.setText("Reportes");

        jmiReporteVentas.setText("Reporte de ventas");
        jmReportes.add(jmiReporteVentas);

        jMenuBar1.add(jmReportes);

        jmUsuario.setText("Usuario");

        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmUsuario.add(jMenuItem1);

        jMenuBar1.add(jmUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpContenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpContenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiMantenimientoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMantenimientoStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiMantenimientoStockActionPerformed

    private void jmiMantenimientoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMantenimientoProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiMantenimientoProductosActionPerformed

    private void jmiMantenimientoCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMantenimientoCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiMantenimientoCategoriasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JDesktopPane jdpContenedor;
    private javax.swing.JLabel jlFechaHora;
    public javax.swing.JLabel jlFechaHoraDatos;
    private javax.swing.JLabel jlUsuario;
    public javax.swing.JLabel jlUsuarioDatos;
    public javax.swing.JMenu jmClientes;
    public javax.swing.JMenu jmProductos;
    public javax.swing.JMenu jmReportes;
    private javax.swing.JMenu jmUsuario;
    public javax.swing.JMenu jmVentas;
    public javax.swing.JMenuItem jmiMantenimientoCategorias;
    public javax.swing.JMenuItem jmiMantenimientoClientes;
    public javax.swing.JMenuItem jmiMantenimientoProductos;
    public javax.swing.JMenuItem jmiMantenimientoStock;
    public javax.swing.JMenuItem jmiRegistroVentas;
    public javax.swing.JMenuItem jmiReporteVentas;
    // End of variables declaration//GEN-END:variables
}
